---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: librephotos
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: reallibrephotos/librephotos-frontend:latest
        ports:
        - name: http
          containerPort: 3000
        securityContext:
          readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
