---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-pvc
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
