apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        resources:
          requests:
            cpu: "250m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "4Gi"
        ports:
        - containerPort: 80
