apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leantime-database
  namespace: leantime
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
