apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: leantume
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: paperless-ngx-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values.yaml
      valuesKey: values.yaml
