---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leantime-ingress
  namespace: leantime
spec:
  defaultBackend:
    service:
      name: leantime
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - planner
