apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leantime-pvc
  namespace: leantime
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
