apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ente-server
  labels:
    io.kompose.service: minio-data
  name: minio-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClass: longhorn
  resources:
    requests:
      storage: 100Mi
