apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ente-server
  labels:
    io.kompose.service: postgres-data
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
