apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values.yaml
      valuesKey: values.yaml
