apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: homarr-1.2.0
      sourceRef:
        kind: HelmRepository
        name: homarr-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
