---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.10.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  values:
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
    installCRDs: true
    webhook:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 50Mi
    extraArgs:
    - --dns01-recursive-nameservers=8.8.8.8:53
    - --dns01-recursive-nameservers-only
    cainjector:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "8.8.8.8"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
