---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: mrb1105@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tailscale-issuer-account-key
    solvers:
    - dns01:
        acmeDNS:
          host: 100.100.100.100
