# yamllint disable
---
apiVersion: v1
kind: Secret
metadata:
  name: gmail-oauth
  namespace: paperless-ngx
type: Opaque
stringData:
    id: ENC[AES256_GCM,data:o6+xjaDWNtomw7KKfMlmMPdrwS9/VGRuoJ4lJVydm+fmBHn6amNCVlb+ULQI/pB02nrEo+p6fh1qCsErUebBm3UJQKqGSFc=,iv:8wU4AHWRATxuq1ov/WJ3GMoRL82ivtgZfzm7JI0U+Uc=,tag:MS3xhNNzNhE4iC6I8A6GxA==,type:str]
    client_secret: ENC[AES256_GCM,data:rsGK+adRABf5Bd8YmSLefmkmeGv6vlrjMib+kM8WJ8NTG88=,iv:XudCDdMYU04fHkGSxBoxwlNsNbRPSJ7iZn3wdnuW0NM=,tag:uV/pP+zxKJAuvQadmjCJ+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-18T23:29:34Z"
    mac: ENC[AES256_GCM,data:FN0WGbKwqjTm6OIarhlYZvogyqUDWQgFEdfmfYHcV2SQ1at3syUARGQT4xPgqxO9+oablwCWzn45p+FwNQNUCMk53YC1lWnxxGjgng5YNJ1jLPj4hBvT9RJuy82/Z6UYiOMLbjRK8NtHtph5EIQazZDIZYRZ+qqt9p0mQ9+iQf8=,iv:zWj2FsdoXY+EdXWuOk4Ye3N9a+Q3k2XxuWEtAZL4MHw=,tag:Fld1V+9fWDcV8izN5uOkhw==,type:str]
    pgp:
        - created_at: "2024-12-18T23:29:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ/+MKOzq9jNZh9RXenG3opduXCvV3nGduz3nz0QnbEB5fnQ
            0pa01C+N9RJqzVeCIWi0XnxMRe40ZDeoifVTAFpYWM4S2G8CtTauFBtnIEqKDeIM
            Dr9OSM4r9atXMC4Co3xgnIgJdBJ5wC0xpIghgeHlh3HuZlZ+rZ94WeTI3ckEY1f7
            vGOlrUQe/o6lOA/rnUH5obZ3UNFh84RVZb4dZCM8FJ1oyCd5jLp5HRkRgW6+hmcO
            GwFKV2bUkcH1rK3cf+cIkyrM78RYrlSY5mTHnfKgV/YsyLaeKir2wvL0tG0qsZ3f
            yRZAXfzZaoi7Zl3vFYd5jx9IilBZ/51HOCb7hRa0XOgwf+oaawfV7iMH32LQPo75
            WCz3WAK+9+Mq4fpxWCyJ9LoHbHJb5do8A25aPBPuJ2BGcje/Bxnor1dMVnOTW+PW
            WPm9xuZK3gvThk9m1BxDeYNFNHNISVl4UNtWqFKfzTtPAC2gyGWBEMPaQzR+gN04
            DHmDQptuW89mtPIw1r+1aJuVbVP6Xx4YegU1wnIMaFoYuAB8mwU6S0h0IySqw8Lz
            akXTK57RkKObWMVNhf3LJcjO5FuofqcE1SaYjCEqV/boe7W5dnqAi0Fjo1twIApO
            +quheae1O/O+ImBfumGHMYE6diSd2pXPXpebgKgwTOUgq5rUUFNcJLQuwJ6L5iLS
            XgGyYcXjNyppvB9xysPJHzsYIsyyNU1ZU4XPCaZJ6BCAKlEgIoOfM/lVbaHiZO5u
            i3yJGlQgGIlLkdy01UiXn9VD6g90k6k8cgr34l08Bb5YzjzvMJZokfBk2aOaifo=
            =vRUr
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
