# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-postgresql
    namespace: paperless-ngx
stringData:
    postgres-password: ENC[AES256_GCM,data:MSKW3B2ye2czNDX6gzwiWWk=,iv:bK10VIxKes++q0Qka9fs+0ihvHCNzEqvbmOyaWui/yo=,tag:ubHjvZbLNHJOoFEfXJSX4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-15T02:13:53Z"
    mac: ENC[AES256_GCM,data:HxGIneeLfNTcOoG8YKKCb/O1hrtSg9wMdgkKj4VgwkLaCNC3dwiL252JPUhB7vBd8T9NAZtjgEx50C0kALh72Zw4UKYJuBD7YYdF9QJOFdXoerK2Zv8ZrCfqf8sbAsXAtMdD4d01DTc2c02dLaGFgRetmw4sEN9ANKNBxdoI31g=,iv:EE/JnSvam/o9slBJqVz0mrUoYqJvcxAME2CHzoO/reE=,tag:2yh0UnlarFE44o8WOB0SmA==,type:str]
    pgp:
        - created_at: "2024-12-15T02:13:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ//fwDIHYku4zWiw+eBGoYfWnu7a1jn7ljHEiK749KeaEN6
            NTCuJaCXuHnvGqRL2DmU1keqMkhBQcFo9rj/nFB8rfgSHdLYSa0XZW515dRcd7g+
            XF0bEK4bCPO/pYoIvlOc3JptEwlzIteoh6/buNmBk50QmccA2TB2mRCQA5jP8mcu
            fc/wXqvvp1PqjX7E5/mT2Twa55yXgLf/viXliXf21AXsRasoiifuvd8OlGO3KsOG
            413ycvJuNzIDaoTilSd0b7HshyT9jayCWG04XbjXVqP6E6/SSknFWCxFi/HnaRbh
            O+Q5IrN58yf5CFFhg42rDH8ezG5WJqGaagvpJzOI2SKBEXW7pUw/Ro5VimMfuMRZ
            xyy6FkyN6q1egMMSvdIblrjwo1XfSYAB3F7wHNV7UBxVfj9VG+RFeQOj6nKms/F6
            Kp4naQqOIPPNMGGnS3BBtC/TU3dJ6qy6oXgiOHP/l3cePN9yv6w83PIIo08TyGd7
            jcqZCoGn+bfXozDih8x77EExfnTp+vskJ2ZSJVo7nzTjSH6TE0KzL8tPZvbTqlMR
            Td4oPkySwZtFv2JN61HHxdWGz8WwPiRde1u6B5lw+g/dDK4NMvnmTycxnIhCVIl/
            +aPiC/s7rzuWXDW5LMQ2/HWGL0Dfmbq2wbZ48d45x5jFyV9mVv745uZ3YaWSHubS
            XgF9ZJRFYk6yOeFVj2aycslQSAH7fyT8zjYZ8E5mA9qIcT/L/GzK5fgjxAcmI+wF
            qgDSMtykjIQ7kodtJB9181Vds6OxboX3/vYnNylWiZcIXhAZnGFfni3i4ClJ/Z0=
            =zJ2A
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
