---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donetick-config-pvc
  namespace: donetick
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
