---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beaverhabits-pvc
  namespace: beaverhabits
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
