---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: librephotos

resources:
  - deployment
  - pvc
  - service
  - ingress
configMapGenerator:
  - name: backend
    envs:
      - config/backend.env

images:
  - name: backend-placeholder
    newName: reallibrephotos/librephotos
    newTag: 2024w40
  - name: frontend-placeholder
    newName: reallibrephotos/librephotos-frontend
    newTag: 2024w40
  - name: proxy-placeholder
    newName: reallibrephotos/librephotos-proxy
    newTag: 2024w40
  - name: postgresql-placeholder
    newName: postgres
    newTag: "13"
