apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ente-server
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: museum
  name: museum
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: museum
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: museum
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: ente-postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: ente-postgres
          image: ghcr.io/ente-io/server
          name: museum
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 2112
              protocol: TCP
          volumeMounts:
            - mountPath: /var/logs
              name: custom-logs
            - mountPath: /museum.yaml
              name: museum-claim1
              readOnly: true
            - mountPath: /data
              name: museum-claim3
              readOnly: true
        - args:
            - TCP-LISTEN:3200,fork,reuseaddr
            - TCP:minio:3200
          image: alpine/socat
          name: socat
      restartPolicy: Always
      volumes:
        - name: custom-logs
          persistentVolumeClaim:
            claimName: custom-logs
        - name: museum-claim1
          persistentVolumeClaim:
            claimName: museum-claim1
            readOnly: true
        - name: museum-claim3
          persistentVolumeClaim:
            claimName: museum-claim3
            readOnly: true
