---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost
  namespace: ghost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
