---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: duin
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
    spec:
      serviceAccountName: diun
      containers:
        - name: diun
          image: crazymax/diun:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: duin-pvc
              mountPath: /data
          args: ["serve"]
          env:
            - name: DIUN_NOTIF_DISCORD_WEBHOOKURL
              valueFrom:
                secretKeyRef:
                  key: webhook
                  name: duin-webhook
            - name: DIUN_NOTIF_DISCORD_MENTIONS
              value: "xavierd"
            - name: DIUN_NOTIF_DISCORD_TIMEOUT
              value: "10s"
            - name: TZ
              value: "America/New_York"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_WORKERS
              value: "20"
            - name: DIUN_WATCH_SCHEDULE
              value: "0 */6 * * *"
            - name: DIUN_WATCH_JITTER
              value: "30s"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
      restartPolicy: Always
      volumes:
        - name: duin-pvc
          persistentVolumeClaim:
            claimName: duin-pvc
