apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
