apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values.yaml
      valuesKey: values.yaml
