apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "3200"
      port: 3200
      targetPort: 3200
    - name: "3201"
      port: 3201
      targetPort: 3201
  selector:
    io.kompose.service: minio
