---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ghost
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        disktype: ssd
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-root-password
        - name: MYSQL_DATABASE
          value: ghost
        - name: MYSQL_USER
          value: ghost
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-root-password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pvc
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 3306
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
