# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:PmGOWuA=,iv:MIxwBhZUOr1+LUmuXvLESnnZnxhxbJ8O1LSRxhajBT0=,tag:dPRKSxnu1nKfK8xxiw8tUQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:6CUZ1cFjrgl1PXr0q7LqbjSQlg==,iv:ViVylXUWZMnhwfxIyQnxm39HdnItCL6OTdN/ibbBFVs=,tag:1Vzcbu8yZD2GdV3YkKk/3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-16T01:57:27Z"
    mac: ENC[AES256_GCM,data:aZXrSiFwLTV439O7VdEOKjjBuSxBj0TH4KCDNuhN+TZyg9zKISt1sBRQBhZvwcplx8lJbkvO3zhQV6o/yalYVDTU3UR7nPvY16UkkQRJjea6MuJFFiK7Yl0SISRmGd/mU7EVrldB9wiUlHWhblqJb9hG3F2OfMu4MeG8YjbJYbM=,iv:E178ABTleKBI2S2qBXU72m/H11Yv3zZne0QgdDzgTqA=,tag:UMef3wuyNyDHda32X0kemA==,type:str]
    pgp:
        - created_at: "2024-12-16T01:57:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ/+M0jE+kbNJ5itOlar2Wf0oIKpEm8PnAVJ+l8SCbYY9a29
            RjiS3J+xph8/mmrJb7JWDn2+iwXxftjhyrKpG63aCIxpsafI/008uoYeRPd5tu8y
            nP0FtC9y4Ju0zScnmHf04XD7fzmJYF99y4Bc/Adlhc1wWwtxBaWX141U7xL9gZG4
            rg1PI31HBBHZBvb+TEUCTuNrHVr3t1i7Qaszv7hrTr87SB3mWAks1qio6x26jlUM
            9ROpoEFjLCQhVFJNs/VvvORRRqnIYFCE878PM1YdkCoxuK65qXC79Bujdace/57h
            e3Mh9rixhWflgpwd5PoC8liXhf6D8nZry0Y+ruzDF/nhd87DtB+5e64vaT9tv6ST
            t+m0BPWbYdCtdWZrBwdyLEq6qcOFjrS+REJmtWBA8I+au0m5Czq7ljZ08YISmHKT
            gA6J+4RklqyH16fK5dznBbJKXfvEf/OZbdyW5RacNhP0h2EFN2DXgBDWTeLEdO2F
            TnG5VvxUMYuVsjSN5qAkWaHOdP5AoRZL2954ouGlmEsGefkkQut1zbwPZZOR/9rX
            0DPQBYuOCE1lPRolPJRPo89iZWP+1Na4SoVpIsQqU0hN9Xev57Oc19LekKqsHfHD
            n7ySdAFTmbJ0ENT3CNU8wYxE+1OysgRQXYTAXTq0+hpMm88iUVvGL9rEcdUfxg7S
            XAGoOa6jBumqy4jGK8cg96W7aKfgF6q3bch3UizbmLXix4g/5BRpBNEvvH0O9ERv
            t4kpArCxepHW/hzJZbI+8gQy0J3cUkS2F43KoeWvmE+Tr0yGiuU9Zx9+rc4e
            =r2c9
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
