---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ghost
  labels:
    app: ghost
spec:
  nodeSelector:
    disktype: ssd
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      env:
      database__client: mysql
      database__connection__host: 10.43.102.50
      database__connection__user: root
      database__connection__password:
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-root-password
      database__connection__database: ghost
      containers:
      - name: ghost
        image: ghost:5
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: ghost-pvc
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 2368
      volumes:
      - name: ghost-pvc
        persistentVolumeClaim:
          claimName: ghost-pvc
