---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ghost
  labels:
    app: ghost
spec:
  nodeSelector:
    disktype: premium-ssd
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      nodeSelector:
        disktype: premium-ssd
      containers:
      - name: ghost
        image: ghost:5-alpine
        env:
        - name: url
          value: https://rmblau.com
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: 10.43.173.218
        - name: database__connection__user
          value: root
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-root-password
        - name: database__connection__database
          value: ghost
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: ghost-pvc
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 2368
      volumes:
      - name: ghost-pvc
        persistentVolumeClaim:
          claimName: ghost-pvc
