---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: ghost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: rmblau.com # your domain
    http:
      paths:
      - backend:
          service:
            name: ghost-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rmblau.com
    secretName: letsencrypt-prod
