---
apiVersion: v1
kind: Service
metadata:
  name: ghost-svc
  namespace: ghost
spec:
  ports:
  - port: 80
    protocal: TCP
    targetPort: 2368
  selector:
    app: ghost
  ClusterIP: 10.43.202.253
