apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values.yaml
      valuesKey: values.yaml
