---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
spec:
  defaultBackend:
    service:
      name: nextcloud
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - nextcloud
