apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
