---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
