---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-journal-pvc
  namespace: adventurelog
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
