# yamllint disable
---
apiVersion: v1
kind: Secret
metadata:
    name: adventurelog-secret
    namespace: adventurelog
type: Opaque
stringData:
    adventure-postgres-password: ENC[AES256_GCM,data:vjjTTrrjfjV1FkMG,iv:wxOTgIB0cw+jxsNuF/53yqoTg+4C+kdd2E+k92omNqc=,tag:Y+6Ee3rMNsiaZWEN9+7m7A==,type:str]
    django-password: ENC[AES256_GCM,data:1yWX+B9ZU5K4+aRmx8mXLXIKcg==,iv:M/bVjGSQbCsIAJExKhp0dpyCvKhBGbr/xa1dnOc3nr4=,tag:0qxM4KP1EsDnJMHw+1sbSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-19T01:08:21Z"
    mac: ENC[AES256_GCM,data:1Jn0J2+9xoCItwED3Q6HT9OXdwt4zQc4laaA70eQezH70xPLjXO+gpjQeHoTBhgfslLP3gUhULYMrI+7hZ8IiZbA8L85DzlgxwN8vBVXiE97NcdeYVVMIyGMAcyVLY33vql6OemH0SKee/Nt/A3i77NZE6ZeEWfj4QbKsHl0/Xs=,iv:W9skI4LM4qRAZuDOyNgNB+8vU7EGhQef+5EfugfIWnk=,tag:rTdNZ9rdgsFJy9R2eH73IQ==,type:str]
    pgp:
        - created_at: "2025-01-19T01:08:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAARAAl0xkUGGvIn0FqnEWY7f13pvuNI3CaINHnJbiR8ia3EFf
            p9r1dpAaAKtnuFAugsm6z9KHT3cY3wRzEkmrH3co7NtQdPBvluRKq2dAQPlmUQvm
            1J8zoGGQFVmaxc2wtjpUGcS6CvziDfLFQ84dt6UhMRzW6D/FnZVn49EC3RRByMrE
            BnpP1ONUqTh/hC9+PKqehB+F81s3y0hsaP3CfC+J2+3iPQG2wqzdcvbMMSoI0yT1
            PJ5KD1pOJmEOTuY4GZe2+1hg5ak90v0a+hckQBAmAU4+PL2Vz04forz06DMCc131
            D2MNhh1Fno/Hs68APwbmjmjASznMfPyPbE1oqaxoW962OTEgq2iaiG63HJXKPP3a
            sovqwMXfRaDOpRosOPxN3f9PVxWUg4koI9ACJTLs1YZzHFfqIQmu9LQpq6rrhh7j
            Yrw9IRhmON7wu6zIkEnTn5Ar2lSZpdgg6ZvEg8dHipfvhZnVhYPtj9SQd8zBzWwZ
            HnR/cqVRUkgE5GncNKeD5UVl9x9wuxCSnPmojcxRDYRmN1q9w4Lbj6M6Lprn/kkV
            ptxkxf6qLCyF3ynTGjXnbNCsPtTmrSVL2a1Jv4XnpqBzM/7sq0WZF5fx95Zr6a6T
            6ggUod9NsEyFupTwKBGRtjyCT48iKFVkCrNIf6bwxA/5GC7p1BC2VXogcaTZ2AnS
            XAFQVngMM0tRZHti2k2g14aklUuCPhTQg9fbg6EC+apQTXQpY5pGQEZninjdi3MH
            DKKicTAaW0c6LVdlXjRvtFruNaf+DNpbOXjI4zjw5MhVJ7tn4kKREfEmBwqU
            =+YfD
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
