apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-pvc
  namespace: grocy
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
