apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-wyze
  namespace: home-assistant
spec:
  defaultBackend:
    service:
      name: wyze-home-assistant-bridge
      port:
        number: 5000
  ingressClassName: tailscale
  tls:
  - hosts:
    - wyze
