# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: librephotos
stringData:
    DB_PASS: ENC[AES256_GCM,data:Gyf4Fjm4f9l2+H+W0FBZF3m+hUtu2Yv7Q0GeLlL+zGM=,iv:xqGGxabAwFd7tkSTpRdbSfTc3gaVOiNjRso8pj8hvOU=,tag:GZTAeZEGHJFqRypTWz9OoQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:av5TiqTC/RZkyTc=,iv:KG+gsw0XyD9DRHnpww9iKuBeZdmpovy7YH171j5LPvQ=,tag:Vgs3Suvz4T6Ay689DjpO3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-01T02:57:58Z"
    mac: ENC[AES256_GCM,data:dqbL66eRwPwAEX6ZMC9AdjjAiIg2HRNMB3/k9SHR1mXXWCuu2bm9bwoVY57GK3lMkb2ZhaN9uw0T+f1E+QU/n6tnakyh5Ule+RORTTuwCVoAN8j3kKWZZMmHoZmk3ZOb0OT5hOUr58mU+cI32oDw0FeiQrrNrB9MExkhlJ8AcR0=,iv:pCZrNkYntjVz+y4/6QORaMrLs32zz3wtsXA3q8VpHUk=,tag:dQMoERVmuxI39MMKSZjlzg==,type:str]
    pgp:
        - created_at: "2024-11-01T02:57:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAARAApioW/5LYWY2mBwavaTncI9Mdk6gZ9oUHtf8yOu49yoGE
            hEo6K0+zy370kXhWtumqD/UWj7VmWD4Qgnjpu0XBcXGuMVag/SiRYm+z5xkG0z36
            HfKX667MbSoKaYt16cpp79t3fNo0VkEshxBzKrqcrgvFgIeLojM54OuM/xZxt4y7
            l7NYxxVHU4r/OwDmRtXr2mOLsYKm+jHJGYEq9jWrEQD+XbyDRV3EnM40mdVh+bp9
            4NTHOSGqEJ4+3Wo30lN65WKZXRPMdsYk7JuV9tqn6733U9h/J36BevBZA5Gna6gw
            IKBNHjHORHjblYK406nxpdvHNJd41GgAO3Q4PbUdZz/3YAJyYYe73OtV0IUp3t2F
            95xylySJH9hIvp0JIVf9pXqiULVHHCzMb9EEky686+jmL+rBGRk02SDs18xQsmTs
            nXZnP/kbOUFpjAI6wnQrOhGW2GO6s7Ebe0/AJax1zxa5fbgnIN+QNWJun2qIxw+2
            hEfaJZjt8obbORmJBoURaE1NXSG8/UhFSA9cU+lafAZiQdaFpJ1nC/Ns/IcTxC0P
            GdeTRl/FP1ht44r6G0SigVpxSL50O2ZvCJIxpsZOWMVWALp3tgMVEOwGC3GKooGZ
            YXjpNcCl1Szo6JgAXFIHX20Fc8T96tieaq/LRiNv/C6YDKkL2+MsQ/jqh/vp5HfS
            XgEMEwi/12xSTOj8h3NSBs1nOdA5cifEyFTY8PDJoUC3lULWIK9RUeV+iXBVR+A+
            ZPhKF6ccHnrlxbt9COC9PfgCICHkJhgzDU7eBPBnjF6UbUWbctFicPBrWvTBYNA=
            =SU/C
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
