# The postgres volume holds all the metadata. If it's 1% the size of "photos," you're probably fine.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: librephotos
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
