---

# This volume contains thumbnails. Setting it to 10-15% the size of "photos" is probably reasonable.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protected
  namespace: librephotos
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
