apiVersion: v1
kind: Service
metadata:
  name: wyze-home-assistant-bridge
  namespace: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant-wyze-bridge
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
