apiVersion: v1
kind: Service
metadata:
  name: wyze-home-assistant-bridge
spec:
  selector:
    app.kubernetes.io/name: home-assistant-wyze-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
