---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librephotos-ingress
  namespace: librephotos
spec:
  defaultBackend:
    service:
      name: proxy
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - librephotos
