---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`raspberrypi.tail9dea6.ts.net`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
