# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-b2
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tJh5swABpIKT34L7,iv:mtsJt49vxNK5mvirvJ85Hm5f4LbWrKF1gFviNYPXNDs=,tag:/+UFUuU6qWFferHgacIPeA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Pb9pVU0yw3q8XvMyszvggHbVb94u3c/6kDiOfayyHw==,iv:TDIH6wQImMdCLmjFS7b0/vS4G1S1vEC6mTx3N0ELjTc=,tag:ekmVdXqFCF0O+K+RXUK0sw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:40+h7sNzSpa/zVQYdRvNbHUs1r+wMYwGAijQqfrp,iv:RA/V2umj8ka9ncyHUrcMi5Q6lZTrCIvK7Xzoi4y6k7I=,tag:skM3IrpsTg9tg+csCsHlUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-12T01:36:15Z"
    mac: ENC[AES256_GCM,data:XlQyJOHvngolt5nmIAjqBfv4+BAG3MyZ15XC1RNaVz10waMPLLnjofDC7rCj6W/tVtGrhds3zI9EReHtJp29jrlmGpcmB8chAK5IZvPrB+Cgn3xqwwIi5uhv+8u7Ih/yw0ZBAOkFMJDCedWWDQDxhi5FqT79yiaoQlGkkM8vgvs=,iv:Zku8rBg1HMt50YF1NJCznDxV4SG5fc3QVuO4lIfOu58=,tag:6LaRc66cX/6FQ1hOYEFHQw==,type:str]
    pgp:
        - created_at: "2024-11-12T01:36:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ/+L1tgpQ9iYyqqK6vMHs+x3oVbUDEJ++Op5EfC09GaktWK
            uRYR20u0/VCKKw3qZ58wbNzo3ys8Agd0JasEZTYYDvNKbyD2mLtIT5SLhbi2FzGF
            nBcZQ59xB3b2Zns+RH0kcJgAMcXcCSS9RuuYsl0dcazX6/svfzy1VjZYERt3Y/D5
            ma0bCfthSHGOC1zeits7qzRSj2+uNLGLohgl0ym3gnArfi/+FBRAnbhINgrcv0l1
            snFzhGGSsnT3YzPdKpdo+IGYef+xoIPFbsgLhJd0xMnGJ5bNxvKdYQZ335AjMGnS
            zZ+UoXR1ZzvtvQAS1Z8Xyf5ypFwUve/k3Mx4trt05B1YfNYU1bnZcW/LxHk22vpy
            amyICjAWcdHj662SaiKfKmbAM649p/18gUmv1IwsVmG/uzTfxTySSAUbeuiMuqOg
            w3/yvL4wWaXb3iaTNrQLxkC8GvTnDDNWBwmEh1wTgnFU9jXqgfi82/omSFs3jFgE
            Sew4VuOfjbBDfYzkoHWD1wV+MYW4Vr/c93o4OhM1DfkruqrS6e8LsvEhWfbviNui
            XwReHEY3PHXwCl26WAjV0PQV8gZKQwDwuWjxoL0BVYxKTD8khmw0uh2vgGuAaOKY
            ed7/rLZtOnFj/5R0VdU/6pU8aTw1J9HMSzLYTKJ0cHtfNoym7NRdQSzYWqjWaMnS
            XgHYbnjrnDxnYo5ShIA06x2eiJzIn2VvSj6pkEp0FbxyX5JJbgJ1FMVrg7Crk0k+
            ma9eR1YRVJsIUeSChPUg2FZiTb97uZDo4UNOIEZYEfBeRFOCBi1IxoWmuYJfTLg=
            =4j1u
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
