# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backblaze
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/XGWO6kODguY5iQ2,iv:WoQzwo0bCvunESRhvIhoOvVS5kTnbozCY2p8lIF97VA=,tag:XIxwNizEBOL3zKEw7HVDVQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P+KZ8Fn4yfWLZf3yqaDEzMWWQ26a99yNWKntz4SC+g==,iv:a27ntfHFVO4h4tdmhYru+nF3LIQzfDYfJQhtODOVsqI=,tag:O37Wa6fqBDJC6JpGTwrrxw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:JYYsTC78mfIC74j9EsJJlP7KgOlq4AifhONqkEiF,iv:ZifjxdixQjwAR49AsaoDTAtDv+tCWrQZOF0YeTdeV80=,tag:zGKso56vjjjhtgEANAUwxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-12T01:42:02Z"
    mac: ENC[AES256_GCM,data:y4Hsw0ExucAiyLYldBjmRNTJXFrdtKlmJutvP7NUxuRg5Rh+22jnUhHprCQhAd1kKdmluOebDatvDXhhdARUvymAVAYPoaz3cSH7d88kUzKl6RK+ZQrZ4h0IxLToRawD2Tks+8n9uFdJHhm6WqGG2jXPM04JiZXq12XvSDgTYK4=,iv:tDVmhNX89cSBOMJ6Mwapv+v+qTMZtNX/VG77I5jcTYQ=,tag:sjcTcJFqkJJSoBpoXToxLQ==,type:str]
    pgp:
        - created_at: "2024-11-12T01:42:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ/8DMaZoP1i94FL15wSo/B5Mn/KRr3muzRb7U44vuSn+waa
            GxkfqbSDSYmSvQzH3Z+EsVy86z/V3Ud9EaeKXjAK+jPnCNt1vyGIhIJfmjJFkprt
            eNDEri8mYPdXgfwzdcxeFk2APZTT7Avrrr0jwbG+7oNYyAG4ETW2dqVq70Yp6bkA
            XL9QJTsfJS6uWjxuOY3pUaAzVOMIgAwg8tEWjE0dPaJ8ZDYuGlsjjIC9xsklRzrB
            2s4WHBMlpCVahHkpPbkpM5wAR7UjF3B/AbgqRqVhN2sey2ZTduvR75Z73QhniPTh
            Jvsd9Ugq3rvZpJfp8O+5LwEDqkBsUbeonU8aG4d5G9rvczKwEsLMD8QgHx69g21C
            s2cCwb4F7KM+iHPfHpFbFOlhXLqpZqe5P9DIVHSkL1EtKs2dUtwGmogC+qWHWDg1
            XrMJ1rekgXgN2xmKd34d50mV9tp2OeAcagkWPlzMcQRAdv+Zif7fzGe+3xnwdVps
            PX28KxvuQ1mK0TTJ5tJHFd9588I/2n2jbMycIACqU4ozrWDLb9wcExujPros+nwV
            XJj2nTXxx4AWg0iIC6VgVnG93nN9uMfCCOIrO91xYgr+Vi47logJ7qWBk4+He8bt
            IMVvzkyIhn8qLxWDdcT6EK5LjebjbFXOmKmQsRgoyvvFpEgK07SENu5pwdDDmQTS
            XAEukNf3pVESmvedLymyCF5HCwQdx82pH/syjinIaeeg7VIXnX6o5TODZetWMQXl
            DMpS9YcwDO2wZLVLcEnwAaWLakemnkaNF6X8pGKvk/wSZgPqwzRzsy5w48PV
            =Y/xY
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
