# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backblaze
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sYdGDLgtQs0r7RApTWgMOtc4JZT5v4JH9Q==,iv:8XtWGRHsl8kqQilmg2k2JHjgrjiHUL/lqxqED0klW2A=,tag:46uv3dgzrd78IUIYpjQIBQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7yQpUY/U9ky8qfEv9bj4rq84wmgrpnCvMyjBsd/bEA==,iv:U6jKvYciUBbGK4CtWYSxylt3Wo7dXvMo+hHswUcG3iQ=,tag:ik31oCflGI9i3jXzwZsbDA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:kfIC347SXuqoNFLpjL7mDLwjl/cUMWDhwx7tRt/i,iv:Tc5vAcFiDuzpO2MtwcO0kQvb8+rmAtZ5dPi23tnlYlU=,tag:duSEmbqmMZqcFY2RY27GxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-12T01:58:51Z"
    mac: ENC[AES256_GCM,data:xMBgxGSdHKqI5IG39eaena0weQSW1OsFYJ1ze7jnh+u2qGM0VhETXBZiqwmjAR0v7yo451NQNlX58mTyCsqeUFWHM+JaaFFIJO7fCtYgu0A9nvAEeY9PpOmLTAO5Mst0Y79+LeYwFaoHJhup692bbX69kgD3RI9cOVgDAsA4eJk=,iv:4S3Ee8Hc5VpsPeFMABf5Y6pSy2HvrXsYpbIJTFZsSzo=,tag:n8f8vd/3s9d6svd9HfqXXQ==,type:str]
    pgp:
        - created_at: "2024-11-12T01:58:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8qPtDiah3jAAQ/9FD56ldd/pS/VkbiIZCltZvWde0In3UH2oBYXbcllyYID
            jOdbHWaec8RO97RdFV0BV3xTkujdyQEgLxQDnV0ze72O7PbzpykmzUipv+LorBSC
            rdUNOdoOWPI1LyjTifWJUeopQt/9XU0KzIgN+Ew9u9kzSuC3QrzG/MwyQsUbXiwN
            gW1i+mQwoR+rznQvPJ3ZLvytOBr30/8zlvzVEhhHcwICwVP/daJBBASJtys4kUuh
            O5HJ+K3rlnCY+3Hd0/F8Asqy3zuNpD5+W/TRHsimQ2lwcuuRLgMyfiSTD5KjNrdR
            igccaLjsppfpXvfLwcnPVBAGiCWJfI9VkRYSdzk4tyyrXdhBzIHJGvPTW9imtxVd
            Er4Tr9BW38sv2LASz5zkbcb30bAxBlGXTKm09qUePXQYyr42pteIXidimldPvMFj
            KDa3lscYmnvTZU9UDCm68Ksuf9inxA02OyPumslgnh8ERReQ1na33RgYCsS7g1Ir
            BWJLg3RxH6ijVPzQlsH/PYRbyk8omIQbxQ4YnCfO5HBkzHalEQ46SD+U4dr7sxiZ
            qFSQOURbkCVJUqYiCTKAMZhst4kqvMrYsiDg99sys1IoNfd188ZacueRDNYQH+40
            l7jKl5WY1nH050GKh6OFai74i4mle3PJIAFXSE/9bTgyN8zW9+zXDWXaWNU3/zzS
            XgEOZ4AbZIDAV+n/zH9Jgxa7YRweRO4J5y7Lc82tCEB/kU3NoO0RjiK1jZlJO4RG
            REFgo1hfUXkyh8w6fol99tuIrPINB/9p+2WeYi1kGIhElZDgRCOP15PAt81hjrc=
            =dpDx
            -----END PGP MESSAGE-----
          fp: B9DBB5EBB5CC92204899530484AE73EC874A540D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
