apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
spec:
  defaultBackend:
    service:
      name: home-assistant
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - home.assistant
