---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: raspberrypi.tail9dea6.ts.net
      http:
        paths:
          - path: /home-assistant
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
