apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: minecraft-data
          mountPath: /minecraft
        env:
        - name: MaxMemory
          value: '5120'
        - name: k8s
          value: "True"
        - name: enable-proxy-protocol
          value: "False"
        resources:
          limits:
            cpu: 1500m
            memory: 5120M
            ephemeral-storage: 50Mi
          requests:
            cpu: 750m
            memory: 4096M
            ephemeral-storage: 2Mi
        ports:
        - containerPort: 25565
          name: java
        - containerPort: 19132
          name: bedrock-v4
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc
