apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ingress
  namespace: minecraft
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: minecraft.rmblau.com
      http:
        paths:
          - path: /
            pathType: Prefix
            defaultBackend:
              service:
                name: minecraft-minecraft
                port:
                  number: 80
