apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    - name: java
      port: 25565
      protocol: TCP
      targetPort: java
    - name: bedrock-v4-udp
      port: 25565
      protocol: UDP
      nodePort: 30001
      targetPort: bedrock-v4

  selector:
    app: minecraft
